version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" # Porta principal para os serviços da AWS
    environment:
      - SERVICES=sns,sqs
    volumes:
      - "./localstack-data:/var/lib/localstack"
